// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbboqmhglbvfczfumard.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiYm9xbWhnbGJ2ZmN6ZnVtYXJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjM5MTcsImV4cCI6MjA3MDM5OTkxN30.-o1_VFtVVrwj-8TOQjVNqjkHDZOLarQCbWHvNtCrkPo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});